<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                                'rel' => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico'
                            ])->prependStylesheet('/css/style.css');
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <header>
            <ul>
                <li id="nav-title"><a href="/">netsoccer</a></li>
                <li class="nav-item"><a href="/news">news</a></li>
                <li id="nav-signup"><a href="/register">sign up</a></li>
                <li class="nav-item"><a href="/login">log in</a></li>
            </ul>
        </header>
        <main>
            <?= $this->content; ?>
        </main>
        <footer>
            <div>
                <h2>netsoccer</h2>
                <h4>connecting football talents</h4>
            </div>
            <p>2021&copy; Huanga IT Solutions AG</p>
        </footer>
    </body>
</html>